export const aromsListTpa = [
  {id: 1001, name: 'Absinthe (Абсент)', selected: false },
  {id: 1002, name: 'Acai (Ягода асаи)', selected: false },
  {id: 1003, name: 'Acetyl Pyrazine (Ацетил пиразин)', selected: false },
  {id: 1004, name: 'Almond (Миндаль)', selected: false },
  {id: 1005, name: 'Apple (Яблоко)', selected: false },
  {id: 1006, name: 'Apple (tart granny smith) (Яблоко (Гренни Смит))', selected: false },
  {id: 1007, name: 'Apple Candy (Яблочный мармелад)', selected: false },
  {id: 1008, name: 'Apple Pie (Яблочный пирог)', selected: false },
  {id: 1009, name: 'Apricot (Абрикос)', selected: false },
  {id: 1010, name: 'Banana (Банан)', selected: false },
  {id: 1011, name: 'Banana Cream (Банановый крем)', selected: false },
  {id: 1012, name: 'Banana Nut Bread (Банановый хлеб)', selected: false },
  {id: 1013, name: 'Bananas Foster (Банановый фостер)', selected: false },
  {id: 1014, name: 'Bavarian Cream (Баварский крем)', selected: false },
  {id: 1015, name: 'Berry Crunch (Ягодные хлопья)', selected: false },
  {id: 1016, name: 'Bitter Nut Extra (Горький орех)', selected: false },
  {id: 1017, name: 'Bittersweet Chocolate (Биттерсвит шоколад)', selected: false },
  {id: 1018, name: 'Black Cherry (Черешня)', selected: false },
  {id: 1019, name: 'Black Currant (Черная смородина)', selected: false },
  {id: 1020, name: 'Black Honey (Черный мед и табак)', selected: false },
  {id: 1021, name: 'Black Tea (Черный чай)', selected: false },
  {id: 1022, name: 'Blackberry (Ежевика)', selected: false },
  {id: 1023, name: 'Blue Raspberry (Голубая малина)', selected: false },
  {id: 1024, name: 'Blueberry (Extra) (Черника)', selected: false },
  {id: 1025, name: 'Blueberry Candy (Черничные леденцы)', selected: false },
  {id: 1026, name: 'Blueberry Wild (Дикая черника)', selected: false },
  {id: 1027, name: 'Boysenberry (Шелковица )', selected: false },
  {id: 1028, name: 'Brandy (Бренди)', selected: false },
  {id: 1029, name: 'Brown Sugar (Коричневый сахар)', selected: false },
  {id: 1030, name: 'Bubblegum (Жвачка)', selected: false },
  {id: 1031, name: 'Bubblegum (Fruity) (Жвачка (Фруктовая))', selected: false },
  {id: 1032, name: 'Butter (Масло)', selected: false },
  {id: 1033, name: 'Butterscotch (Ирис)', selected: false },
  {id: 1034, name: 'Cantaloupe (Канталупа)', selected: false },
  {id: 1035, name: 'Cappucсino (Каппучино)', selected: false },
  {id: 1036, name: 'Caramel (Карамель)', selected: false },
  {id: 1037, name: 'Caramel (Original) (Карамель (Оригинальная))', selected: false },
  {id: 1038, name: 'Caramel Candy (Карамельная конфета)', selected: false },
  {id: 1039, name: 'Caramel Cappuccino (Карамель-каппучино)', selected: false },
  {id: 1040, name: 'Chai Tea (Чай)', selected: false },
  {id: 1041, name: 'Champagne (Шампанское)', selected: false },
  {id: 1042, name: 'Cheesecake (Чизкейк)', selected: false },
  {id: 1043, name: 'Cheesecake (Graham Crust) (Чизкейк (корочка))', selected: false },
  {id: 1044, name: 'Cherry Blossom (Цветущая вишня)', selected: false },
  {id: 1045, name: 'Cherry Extract (Экстракт вишни)', selected: false },
  {id: 1046, name: 'Chocolate (Шоколад)', selected: false },
  {id: 1047, name: 'Cinnamon (Корица)', selected: false },
  {id: 1048, name: 'Cinnamon Danish (Корица датская)', selected: false },
  {id: 1049, name: 'Cinnamon Red Hot (Корица)', selected: false },
  {id: 1050, name: 'Cinnamon Spice (Острая корица)', selected: false },
  {id: 1051, name: 'Cinnamon Sugar Cookie (Печенье с корицей)', selected: false },
  {id: 1052, name: 'Citrus Punch (Цитрусовый пунш)', selected: false },
  {id: 1053, name: 'Clove (Гвоздика)', selected: false },
  {id: 1054, name: 'Cocoa Rounds (Шоколадные шарики)', selected: false },
  {id: 1055, name: 'Coconut (Кокос)', selected: false },
  {id: 1056, name: 'Coconut (Extra) (Кокос (Экстра))', selected: false },
  {id: 1057, name: 'Coconut Candy (Кокосовые конфеты)', selected: false },
  {id: 1058, name: 'Coffee (Кофе)', selected: false },
  {id: 1059, name: 'Cotton Candy (Сладкая вата)', selected: false },
  {id: 1060, name: 'Cranberry (Клюква)', selected: false },
  {id: 1061, name: 'Cream Soda (Крем-сода)', selected: false },
  {id: 1062, name: 'Creme de Menthe (Сладкий мятный ликер)', selected: false },
  {id: 1063, name: 'Cucumber (Огурец)', selected: false },
  {id: 1064, name: 'Dairy/Milk (Молоко)', selected: false },
  {id: 1065, name: 'DK Tobacco Base (Табак)', selected: false },
  {id: 1066, name: 'Double Chocolate (Clear) (Двойной шоколад)', selected: false },
  {id: 1067, name: 'Double Chocolate (Dark) (Двойной шоколад (Темный))', selected: false },
  {id: 1068, name: 'Dragonfruit (Драгонфрут (питайя))', selected: false },
  {id: 1069, name: 'Dulce de Leche (Сгущенное молоко)', selected: false },
  {id: 1070, name: 'Earl Grey Tea (Эрл-грей)', selected: false },
  {id: 1071, name: 'Elderberry (Бузина)', selected: false },
  {id: 1072, name: 'Energy Drink (Энергетический напиток)', selected: false },
  {id: 1073, name: 'English Toffee (Тоффи)', selected: false },
  {id: 1074, name: 'Espresso (Эспрессо)', selected: false },
  {id: 1075, name: 'Ethyl Maltol (Этил мальтол)', selected: false },
  {id: 1076, name: 'French Vanilla (Французкая ваниль)', selected: false },
  {id: 1077, name: 'French Vanilla Deluxe (Французкая ваниль (Делюкс))', selected: false },
  {id: 1078, name: 'Frosted Donut (Пончик)', selected: false },
  {id: 1079, name: 'Fruit Circles (Фруктовые кольца)', selected: false },
  {id: 1080, name: 'Fruit Circles With Milk (Фруктовые кольца с молоком)', selected: false },
  {id: 1081, name: 'Fruity Stick Gum (Жвачка (Fruity Stick))', selected: false },
  {id: 1082, name: 'Fudge Brownie (Брауни)', selected: false },
  {id: 1083, name: 'Ginger Ale (Имбирный Эль)', selected: false },
  {id: 1084, name: 'Gingerbread (Имбирный пряник)', selected: false },
  {id: 1085, name: 'Graham Cracker (Грэхем крекер)', selected: false },
  {id: 1086, name: 'Graham Cracker Clear (Грэхем крекер)', selected: false },
  {id: 1087, name: 'Grape Candy (Виноградные леденцы)', selected: false },
  {id: 1088, name: 'Grape Juice (Виноградный сок)', selected: false },
  {id: 1089, name: 'Greek Yogurt (Греческий йогурт)', selected: false },
  {id: 1090, name: 'Green Apple (Зеленое яблоко)', selected: false },
  {id: 1091, name: 'Green Tea (Зеленый чай)', selected: false },
  {id: 1092, name: 'Guava (Гуайява)', selected: false },
  {id: 1093, name: 'Gummy Candy (Тянучки)', selected: false },
  {id: 1094, name: 'Hazelnut (Лесной орех)', selected: false },
  {id: 1095, name: 'Hibiscus (Гибискус)', selected: false },
  {id: 1096, name: 'Honey (Мед)', selected: false },
  {id: 1097, name: 'Honeydew (Медовая дыня)', selected: false },
  {id: 1098, name: 'Honeydew II (Медовая дыня (версия 2))', selected: false },
  {id: 1099, name: 'Honeysuckle (Жимолость)', selected: false },
  {id: 1100, name: 'Horehound (Шандра)', selected: false },
  {id: 1101, name: 'Huckleberry (Хаклберри)', selected: false },
  {id: 1102, name: 'Irish Cream (Ирландские сливки)', selected: false },
  {id: 1103, name: 'Jackfruit (Джекфрут)', selected: false },
  {id: 1104, name: 'Jamaican Rum (Ямайский ром)', selected: false },
  {id: 1105, name: 'Kalua and Cream (Калуа и сливки)', selected: false },
  {id: 1106, name: 'Kentucky Bourbon (Бурбон из Кентукки)', selected: false },
  {id: 1107, name: 'Key Lime (Лайм)', selected: false },
  {id: 1108, name: 'Kiwi (Киви)', selected: false },
  {id: 1109, name: 'Kiwi (Double) (Киви (двойной))', selected: false },
  {id: 1110, name: 'Koolada 10 PG (Кулада)', selected: false },
  {id: 1111, name: 'Lemon (water soluble) (Лимон)', selected: false },
  {id: 1112, name: 'Lemon 2 (Лимон (Версия 2))', selected: false },
  {id: 1113, name: 'Lemon Lime (Лимон-лайм)', selected: false },
  {id: 1114, name: 'Lemon Lime 2 (Лимон лайм (версия 2))', selected: false },
  {id: 1115, name: 'Lemonade Cookie (Лимонадное печенье)', selected: false },
  {id: 1116, name: 'Lucky Leprechaun Cereal (Зефирные хлопья)', selected: false },
  {id: 1117, name: 'Lychee (Личи)', selected: false },
  {id: 1118, name: 'M Type Premium (Эм тайп премиум (табак))', selected: false },
  {id: 1119, name: 'Malted milk (Сухое молоко)', selected: false },
  {id: 1120, name: 'Mango (Манго)', selected: false },
  {id: 1121, name: 'Maple Extract (Кленовый экстракт)', selected: false },
  {id: 1122, name: 'Maple Syrup (Кленовый сироп)', selected: false },
  {id: 1123, name: 'Marshmallow (Маршмеллоу)', selected: false },
  {id: 1124, name: 'Mary Jane (Мери Джейн)', selected: false },
  {id: 1125, name: 'Menthol liquid (Ментол)', selected: false },
  {id: 1126, name: 'Meringue (Безе)', selected: false },
  {id: 1127, name: 'Milk Chocolate (Молочный шоколад)', selected: false },
  {id: 1128, name: 'Mojito Havana (Мохито)', selected: false },
  {id: 1129, name: 'Molasses (Меласса)', selected: false },
  {id: 1130, name: 'Musk Candy (Конфеты Musk Lifesaver)', selected: false },
  {id: 1131, name: 'Nectarine (Нектарин)', selected: false },
  {id: 1132, name: 'Oatmeal Cookie (Овсянное печенье)', selected: false },
  {id: 1133, name: 'Orange Cream (Апельсиновый крем)', selected: false },
  {id: 1134, name: 'Orange Mandarin (Мандарин)', selected: false },
  {id: 1135, name: 'Pancake (Панкейк)', selected: false },
  {id: 1136, name: 'Papaya (Папайя)', selected: false },
  {id: 1137, name: 'Passion Fruit (Маракуйя)', selected: false },
  {id: 1138, name: 'Peach (Персик)', selected: false },
  {id: 1139, name: 'Peach (Juicy) (Сок персика)', selected: false },
  {id: 1140, name: 'Peanut Butter (Арахисовое масло)', selected: false },
  {id: 1141, name: 'Pear (Груша)', selected: false },
  {id: 1142, name: 'Pear Candy (Грушевые конфеты)', selected: false },
  {id: 1143, name: 'Pecan (Орех Пекан)', selected: false },
  {id: 1144, name: 'Peppermint (Перечная мята)', selected: false },
  {id: 1145, name: 'Pie Crust (Корочка пирога)', selected: false },
  {id: 1146, name: 'Pina Colada (Пина Колада)', selected: false },
  {id: 1147, name: 'Pineapple (Ананас)', selected: false },
  {id: 1148, name: 'Pistachio (Фисташки)', selected: false },
  {id: 1149, name: 'Plum (Слива)', selected: false },
  {id: 1150, name: 'Pomegranate (Гранат)', selected: false },
  {id: 1151, name: 'Pomegranate Deluxe (Гранат (делюкс))', selected: false },
  {id: 1152, name: 'Popcorn (Попкорн)', selected: false },
  {id: 1153, name: 'Quince (Айва)', selected: false },
  {id: 1154, name: 'Rainbow Drops (Скиттлс)', selected: false },
  {id: 1155, name: 'Raisin (Изюм)', selected: false },
  {id: 1156, name: 'Raspberry (Малина)', selected: false },
  {id: 1157, name: 'Raspberry (Sweet) (Сладкая малина)', selected: false },
  {id: 1158, name: 'Red Licorice (Красная лакрица)', selected: false },
  {id: 1159, name: 'Red Type II Blend (Ред тайп (табак))', selected: false },
  {id: 1160, name: 'Rice Crunchies (Рисовые хлопья)', selected: false },
  {id: 1161, name: 'Ripe Banana (Спелый банан)', selected: false },
  {id: 1162, name: 'Root beer flavor (pg) (Рутбир)', selected: false },
  {id: 1163, name: 'Root Beer Float (Рутбир Float)', selected: false },
  {id: 1164, name: 'RY4 Double (RY4 (Табак (двойной)))', selected: false },
  {id: 1165, name: 'RY4 Type (RY4 (Табак))', selected: false },
  {id: 1166, name: 'Slim Mint Cookie (Мятное печенье)', selected: false },
  {id: 1167, name: 'Smooth (Smooth)', selected: false },
  {id: 1168, name: 'Sour (Кислый)', selected: false },
  {id: 1169, name: 'Spearmint (Мята колосистая)', selected: false },
  {id: 1170, name: 'Strawberries and Cream (Клубника со сливками)', selected: false },
  {id: 1171, name: 'Strawberry (Клубника)', selected: false },
  {id: 1172, name: 'Strawberry (Ripe) (Спелая клубника)', selected: false },
  {id: 1173, name: 'Swedish Gummy (Шведский гамми)', selected: false },
  {id: 1174, name: 'Sweet and Tart (Кофеты Sweet Tart (Холодок))', selected: false },
  {id: 1175, name: 'Sweet Cream (Сладкий крем)', selected: false },
  {id: 1176, name: 'Sweet Tea (Сладкий чай)', selected: false },
  {id: 1177, name: 'Sweetener (Подсластитель)', selected: false },
  {id: 1178, name: 'Tiramisu (Тирамису)', selected: false },
  {id: 1179, name: 'Toasted Almond (Жаренный миндаль)', selected: false },
  {id: 1180, name: 'Toasted Marshmallow (Поджареный зефир)', selected: false },
  {id: 1181, name: 'Tutti-Frutti (Тутти-фрутти)', selected: false },
  {id: 1182, name: 'Vanilla (Bourbon) (Ваниль бурбон)', selected: false },
  {id: 1183, name: 'Vanilla Bean Gelato (Ванильный заварной крем)', selected: false },
  {id: 1184, name: 'Vanilla Bean Ice Cream (Ванильное мороженное)', selected: false },
  {id: 1185, name: 'Vanilla Cupcake (Ванильный пирог)', selected: false },
  {id: 1186, name: 'Vanilla Custard (Ванильный кастард)', selected: false },
  {id: 1187, name: 'Vanilla Swirl (Ванильный рожок)', selected: false },
  {id: 1188, name: 'Vanillin 10 (PG) (Ванилин)', selected: false },
  {id: 1189, name: 'Waffle (Вафли)', selected: false },
  {id: 1190, name: 'Waffle (Belgian) (Бельгийские вафли)', selected: false },
  {id: 1191, name: 'Watermelon (Арбуз)', selected: false },
  {id: 1192, name: 'Watermelon Candy (Арбузные леденцы)', selected: false },
  {id: 1193, name: 'Western (Вестерн)', selected: false },
  {id: 1194, name: 'Whipped Cream (Взбитые сливки)', selected: false },
  {id: 1195, name: 'White Chocolate (Белый шоколад)', selected: false },
  {id: 1196, name: 'Wintergreen (Мятные кофеты)', selected: false },
  {id: 1197, name: 'Yam (Ямс)', selected: false },
]

export const aromsListCapella = [
  {id: 2001, name: 'Apple Pie (Яблочный пирог)' },
  {id: 2002, name: 'Apple Pie V2 (Яблочный пирог 2)' },
  {id: 2003, name: 'Apricot (Абрикос)' },
  {id: 2004, name: 'Banana (Банан)' },
  {id: 2005, name: 'Banana Split (Банановый сплит)' },
  {id: 2006, name: 'Bavarian Cream (Баварский крем)' },
  {id: 2007, name: 'Blackberry (Ежевика)' },
  {id: 2008, name: 'Blueberry (Черника)' },
  {id: 2009, name: 'Blueberry Cinnamon Crumble (Черничный пирог с корицей)' },
  {id: 2010, name: 'Blueberry Jam (Черничное варенье)' },
  {id: 2011, name: 'Blueberry Pomegranate (Черника и гранат)' },
  {id: 2012, name: 'Boston Cream Pie V2 (Бостонский кремовый пирог)' },
  {id: 2013, name: 'Bubble Gum (Жвачка)' },
  {id: 2014, name: 'Butter Cream (Крем)' },
  {id: 2015, name: 'Cake Batter (Тесто для кекса)' },
  {id: 2016, name: 'Cantaloupe (Мускусная дыня)' },
  {id: 2017, name: 'Cappuccino (Каппучино)' },
  {id: 2018, name: 'Caramel V2 (Карамель 2)' },
  {id: 2019, name: 'Cereal 27 (Кукурузные хлопья)' },
  {id: 2020, name: 'Cherry (Wild) w/Stevia (Дикая вишня и стевия)' },
  {id: 2021, name: 'Chocolate Coconut Almond (Шоколад кокос миндаль)' },
  {id: 2022, name: 'Chocolate Glazed Doughnut (Глазированный шаколадный пончик)' },
  {id: 2023, name: 'Chocolate Raspberry (Малина с шоколадом)' },
  {id: 2024, name: 'Churro (Чуррос)' },
  {id: 2025, name: 'Cinnamon Danish Swirl V2 (Датский завиток с корицей 2)' },
  {id: 2026, name: 'Coconut (Кокос)' },
  {id: 2027, name: 'Cola (Кола)' },
  {id: 2028, name: 'Concord Grape w/Stevia (Конкорд и стевия)' },
  {id: 2029, name: 'Cool Mint (Мятная свежесть)' },
  {id: 2030, name: 'Cranberry (Клюква)' },
  {id: 2031, name: 'Creamy Yogurt (Кремовый йогурт)' },
  {id: 2032, name: 'Double Apple (Двойное яблоко)' },
  {id: 2033, name: 'Double Watermelon (Двойной арбуз)' },
  {id: 2034, name: 'Dragon Fruit (Драгонфрут)' },
  {id: 2035, name: 'French Vanilla (Французкая ваниль)' },
  {id: 2036, name: 'Funnel Cake (Торт "Муравейник")' },
  {id: 2037, name: 'Glazed Doughnut (Глазированный пончик)' },
  {id: 2038, name: 'Golden Pineapple (Золотой ананас)' },
  {id: 2039, name: 'Graham Cracker V2 (Грэхем крекер 2)' },
  {id: 2040, name: 'Grapefruit (Грейпфрут)' },
  {id: 2041, name: 'Greek Yogurt (Греческий йогурт)' },
  {id: 2042, name: 'Green Apple (Зеленое яблоко)' },
  {id: 2043, name: 'Grenadine (Гренадин)' },
  {id: 2044, name: 'Harvest Berry (Лесные ягоды)' },
  {id: 2045, name: 'Hazelnut (Лесной орех)' },
  {id: 2046, name: 'Honeydew Melon (Медовая дыня)' },
  {id: 2047, name: 'Italian Lemon Sicily (Сицилийский лимон)' },
  {id: 2048, name: 'Jelly Candy (Конфеты из желе)' },
  {id: 2049, name: 'Jelly Candys (Конфеты желе)' },
  {id: 2050, name: 'Juicy Lemon (Сок лимона)' },
  {id: 2051, name: 'Juicy Orange (Сочный апельсин)' },
  {id: 2052, name: 'Juicy Peach (Сочный персик)' },
  {id: 2053, name: 'Kiwi (Киви)' },
  {id: 2054, name: 'Kiwi Strawberry (Киви и клубника)' },
  {id: 2055, name: 'Lemon Lime (Лимон-лайм)' },
  {id: 2056, name: 'Lemon Meringue Pie (Лимонный пирог с безе)' },
  {id: 2057, name: 'Maple (Pancake Syrup) (Кленовый сироп)' },
  {id: 2058, name: 'Milk Chocolate Toffee (Шоколаный тоффи)' },
  {id: 2059, name: 'New York Cheesecake (New York чизкейк)' },
  {id: 2060, name: 'New York Cheesecake v2 (New York чизкейк v2)' },
  {id: 2061, name: 'Orange Creamsicle (Апельсиновое мороженное)' },
  {id: 2062, name: 'Orange Mango (Апельсин и манго)' },
  {id: 2063, name: 'Passion Fruit (Маракуйя)' },
  {id: 2064, name: 'Peach w/Stevia (Персик и стевия)' },
  {id: 2065, name: 'Peaches and Cream (Персики в крему)' },
  {id: 2066, name: 'Peaches and Cream v2 (Персики в крему v2)' },
  {id: 2067, name: 'Peanut Butter V2 (Арахисовое масло (версия 2))' },
  {id: 2068, name: 'Pear Flavor (Груша)' },
  {id: 2069, name: 'Pink Lemonades (Лимонад)' },
  {id: 2070, name: 'Pomegranate V2 (Гранат 2)' },
  {id: 2071, name: 'Raspberry (Малина)' },
  {id: 2072, name: 'Raspberry V2 (Малина 2)' },
  {id: 2073, name: 'Simply Vanilla (Ваниль)' },
  {id: 2074, name: 'Strawberries and Cream ( Клубника в сливках)' },
  {id: 2075, name: 'Strawberry Taffys (Клубничный тэфи)' },
  {id: 2076, name: 'Sugar Cookie v2 (Сахарное печенье v2)' },
  {id: 2077, name: 'Super Sweet Sucralose Sweetener (Подсластитель)' },
  {id: 2078, name: 'Sweet Cream (Сладкий крем)' },
  {id: 2079, name: 'Sweet Lychee (Сладкий личи)' },
  {id: 2080, name: 'Sweet Mango (Сладкий манго)' },
  {id: 2081, name: 'Sweet Strawberry (Сладкая клубника)' },
  {id: 2082, name: 'Sweet Strawberry RF (Сладкая клубника РФ)' },
  {id: 2083, name: 'Sweet Tangerine (Сладкий мандарин)' },
  {id: 2084, name: 'Sweet Tangerine Rf (Сладкий мандарин)' },
  {id: 2085, name: 'Sweet Tea (Сладкий чай)' },
  {id: 2086, name: 'Sweet Watermelon (Сладкий арбуз)' },
  {id: 2087, name: 'Vanilla Bean Ice Cream (Ванильное мороженное)' },
  {id: 2088, name: 'Vanilla Cupcake V2 (Ванильный пирог)' },
  {id: 2089, name: 'Vanilla Custard (Ванильный кастард)' },
  {id: 2090, name: 'Vanilla Custard V2 (Ванильный крем v2)' },
  {id: 2091, name: 'Vanilla Whipped Cream (Ванильные взбитые сливки)' },
  {id: 2092, name: 'Waffle (Вафли)' },
  {id: 2093, name: 'Wild Cherry (Дикая вишня)' },
  {id: 2094, name: 'Yellow Peach (Желтый персик)' },
]

export const aromsListFlavourArt =[
  {id: 3001, name: 'Apple Pie (Яблочный Пирог)' },
  {id: 3002, name: 'Bilberry (Черника)' },
  {id: 3003, name: 'Biscotto Cookie (Овсяное Печенье)' },
  {id: 3004, name: 'Blackberry (Ежевика)' },
  {id: 3005, name: 'Blackcurrant (Черная Смородина)' },
  {id: 3006, name: 'Caramel (Карамель)' },
  {id: 3007, name: 'Champagne (Шампанское)' },
  {id: 3008, name: 'Cherry (Вишня)' },
  {id: 3009, name: 'Citrus Mix (Цитрусовый Микс)' },
  {id: 3010, name: 'Classic Vanilla (Ваниль)' },
  {id: 3011, name: 'Coconut (Кокос)' },
  {id: 3012, name: 'Cola (Кола)' },
  {id: 3013, name: 'Custard Cream (Заварной Крем)' },
  {id: 3014, name: 'Forest Fruit Mix (Фруктовый Микс)' },
  {id: 3015, name: 'Fuji Apple (Яблоко Fuji)' },
  {id: 3016, name: 'Green Tea (Зеленый Чай)' },
  {id: 3017, name: 'Hazelnut (Лесной Орех)' },
  {id: 3018, name: 'Kiwi (Киви)' },
  {id: 3019, name: 'Lemon Sicily (Лимон Сицилийский)' },
  {id: 3020, name: 'Lime Tahity Distilled (Лайм)' },
  {id: 3021, name: 'Mandarin (Мандарин)' },
  {id: 3022, name: 'Mango (Манго)' },
  {id: 3023, name: 'Marshmallow (Зефир)' },
  {id: 3024, name: 'Maxx Blend (Табак Maxx Blend)' },
  {id: 3025, name: 'Melon Cantaloupe (Мускусная Дыня)' },
  {id: 3026, name: 'Menthol (Ментол)' },
  {id: 3027, name: 'Meringue (Безе)' },
  {id: 3028, name: 'Nonna’s Cake (Пирог Нонны)' },
  {id: 3029, name: 'Orange (Апельсин)' },
  {id: 3030, name: 'Passionfruit (Маракуйя)' },
  {id: 3031, name: 'Raspberry (Малина)' },
  {id: 3032, name: 'Soho (Табак Soho)' },
  {id: 3033, name: 'Spearmint (Мятная Жвачка)' },
  {id: 3034, name: 'Stark Apple (Яблоко Красное)' },
  {id: 3035, name: 'Strawberry (Клубника)' },
  {id: 3036, name: 'Virginia (Табак Virginia)' },
  {id: 3037, name: 'Watermelon (Арбуз)' },
  {id: 3038, name: 'White Peach (Белый Персик)' },
  {id: 3039, name: 'Yogurt (Йогурт)' },
]


