export const aromsListTpa = [
  { id: 1001, name: 'Absinthe (Абсент)', selected: false },
  { id: 1002, name: 'Absinthe Concentrate (Концентрат Абсента)', selected: false },
  { id: 1003, name: 'Acai (Асаи)', selected: false },
  { id: 1004, name: 'Acetyl Pyrazine 5% (Ацетил Пиразин 5%)', selected: false },
  { id: 1005, name: 'Almond (Миндаль)', selected: false },
  { id: 1006, name: 'Almond Amaretto (Миндальный Амаретто)', selected: false },
  { id: 1007, name: 'Apple (Яблоко)', selected: false },
  { id: 1008, name: 'Apple (Tart Granny Smith) (Терпкие яблоки Гренни Смит)', selected: false },
  { id: 1009, name: 'Apple Candy (Яблочная Конфета)', selected: false },
  { id: 1010, name: 'Apple Pie (Яблочный Пирог)', selected: false },
  { id: 1011, name: 'Apricot (Абрикос)', selected: false },
  { id: 1012, name: 'Banana (Банан)', selected: false },
  { id: 1013, name: 'Banana Cream (Банановый Крем)', selected: false },
  { id: 1014, name: 'Bananas Foster (Банановый Фостер)', selected: false },
  { id: 1015, name: 'Bavarian Cream (Баварский Крем)', selected: false },
  { id: 1016, name: 'Berry Cereal (Ягодный завтрак)', selected: false },
  { id: 1017, name: 'Bittersweet Chocolate (Горький Шоколад)', selected: false },
  { id: 1018, name: 'Black Cherry (Черная Вишня)', selected: false },
  { id: 1019, name: 'Black Currant (Черная Смородина)', selected: false },
  { id: 1020, name: 'Black Honey (Темный Мед)', selected: false },
  { id: 1021, name: 'Black Sesame Seed (Черный кунжута)', selected: false },
  { id: 1022, name: 'Black Tea (Чёрный чай)', selected: false },
  { id: 1023, name: 'Blackberry (Ежевика)', selected: false },
  { id: 1024, name: 'Blueberry (Extra) (Черника Особая)', selected: false },
  { id: 1025, name: 'Blueberry (Wild) (Дикая Черника)', selected: false },
  { id: 1026, name: 'Blueberry Candy (Черничная Конфета)', selected: false },
  { id: 1027, name: 'Boysenberry (Бойзенова Ягода)', selected: false },
  { id: 1028, name: 'Brandy (Бренди)', selected: false },
  { id: 1029, name: 'Brown Sugar (Коричневый Сахар)', selected: false },
  { id: 1030, name: 'Bubblegum (Жвачка )', selected: false },
  { id: 1031, name: 'Bubblegum (Fruity) (Фруктовая Жвачка)', selected: false },
  { id: 1032, name: 'Bubblegum Juicy Style (Жевательная резинка Juicy Стиль)', selected: false },
  { id: 1033, name: 'Butter (Масло)', selected: false },
  { id: 1034, name: 'Butterscotch (Ириска)', selected: false },
  { id: 1035, name: 'Cantaloupe (Мускусная дыня)', selected: false },
  { id: 1036, name: 'Cappuccino (Каппуччино)', selected: false },
  { id: 1037, name: 'Caramel (Карамель)', selected: false },
  { id: 1038, name: 'Caramel (Original) (Карамель (Натуральная))', selected: false },
  { id: 1039, name: 'Caramel Candy (Карамельная конфета)', selected: false },
  { id: 1040, name: 'Caramel Cappuccino (Карамельный Каппуччино)', selected: false },
  { id: 1041, name: 'Chai Tea (Сладкий чай с молоком и пряностями)', selected: false },
  { id: 1042, name: 'Champagne Type (Шампанское)', selected: false },
  { id: 1043, name: 'Cheesecake (Чизкейк)', selected: false },
  { id: 1044, name: 'Cheesecake (Graham Crust) (Чизкейк с печеньем)', selected: false },
  { id: 1045, name: 'Cherry Blossom (Цветущая Вишня)', selected: false },
  { id: 1046, name: 'Cherry Extract (Вишневый Экстракт)', selected: false },
  { id: 1047, name: 'Chicken & Waffle (Вафля с Курицей)', selected: false },
  { id: 1048, name: 'China Tasty (Китайский вкус)', selected: false },
  { id: 1049, name: 'Chocolate (Шоколад)', selected: false },
  { id: 1050, name: 'Chocolate Coconut Almond Candy Bar (Шоколадно-кокосовый миндальный батончик)', selected: false },
  { id: 1051, name: 'Cinnamon (Корица)', selected: false },
  { id: 1052, name: 'Cinnamon Danish (Датская корица)', selected: false },
  { id: 1053, name: 'Cinnamon Red Hot (Острая Корица)', selected: false },
  { id: 1054, name: 'Cinnamon Red Hot (PG) (Корица Red Hot)', selected: false },
  { id: 1055, name: 'Cinnamon Spice (Коричная Специя)', selected: false },
  { id: 1056, name: 'Cinnamon Sugar Cookie (Сахарное печенье с корицей)', selected: false },
  { id: 1057, name: 'Citrus Punch (Цитрусовый Пунш)', selected: false },
  { id: 1058, name: 'Clove (Гвоздика)', selected: false },
  { id: 1059, name: 'Cocoa Rounds (Какао-колечки)', selected: false },
  { id: 1060, name: 'Coconut Candy (Кокосовая Конфета)', selected: false },
  { id: 1061, name: 'Coffee (Кофе)', selected: false },
  { id: 1062, name: 'Coffee (Kona) (Кофе Кона)', selected: false },
  { id: 1063, name: 'Coffee Extra (Clear) (Особое Кофе)', selected: false },
  { id: 1064, name: 'Cola (Кола)', selected: false },
  { id: 1065, name: 'Cola Cherry (Черри-Кола (Вишневая Кола))', selected: false },
  { id: 1066, name: 'Cola Syrup (Сироп Колы)', selected: false },
  { id: 1067, name: 'Cotton Candy (Сладкая Вата)', selected: false },
  { id: 1068, name: 'Cotton Candy (Circus) (Сладкая Вата как в Цирке)', selected: false },
  { id: 1069, name: 'Cranberry (Клюква)', selected: false },
  { id: 1070, name: 'Creme de Menthe (Мятный Крем)', selected: false },
  { id: 1071, name: 'Crunchy Cereal (Хрустящие хлопья)', selected: false },
  { id: 1072, name: 'Cubano Type (Кубинский Вкус)', selected: false },
  { id: 1073, name: 'Cucumber (Огурец)', selected: false },
  { id: 1074, name: 'Dairy/Milk (Молоко)', selected: false },
  { id: 1075, name: 'Double Chocolate (Clear) (Двойной шоколад (чистый))', selected: false },
  { id: 1076, name: 'Double Chocolate (Dark) (Двойной темный шоколад)', selected: false },
  { id: 1077, name: 'Dr. Pop (Доктор Поп)', selected: false },
  { id: 1078, name: 'Dragonfruit (Питайя)', selected: false },
  { id: 1079, name: 'Dulce De Leche (Сладкое молоко)', selected: false },
  { id: 1080, name: 'DX Banana Cream (Банан крем DX)', selected: false },
  { id: 1081, name: 'DX Bananas Foster (Бананы фламбе в карамели)', selected: false },
  { id: 1082, name: 'DX Bavarian Cream (Баварский крем DX)', selected: false },
  { id: 1083, name: 'DX Brown Sugar (Коричневый сахар)', selected: false },
  { id: 1084, name: 'DX Caramel Original (Карамель)', selected: false },
  { id: 1085, name: 'DX Cinnamon Danish (Датская корица)', selected: false },
  { id: 1086, name: 'DX Coconut Candy', selected: false },
  { id: 1087, name: 'DX Hazelnut (Фундук нат.)', selected: false },
  { id: 1088, name: 'DX Milk', selected: false },
  { id: 1089, name: 'DX Milk Chocolate', selected: false },
  { id: 1090, name: 'DX Peach (Juicy)', selected: false },
  { id: 1091, name: 'DX Peanut Butter (Арахисовое масло)', selected: false },
  { id: 1092, name: 'DX Red Velvet', selected: false },
  { id: 1093, name: 'DX Sweet Cream (Сладкий крем)', selected: false },
  { id: 1094, name: 'DX Vanilla Cupcake (Ванильный кекс DX)', selected: false },
  { id: 1095, name: 'Earl Grey Tea (Чай Эрл Грей)', selected: false },
  { id: 1096, name: 'Egg Nog (Эгг-ног)', selected: false },
  { id: 1097, name: 'Elderberry (Бузина)', selected: false },
  { id: 1098, name: 'Energy Drink (Энергетический Напиток)', selected: false },
  { id: 1099, name: 'English Toffee (Английская Ириска)', selected: false },
  { id: 1100, name: 'Espresso (Эспрессо)', selected: false },
  { id: 1101, name: 'Ethyl Maltol 10% (Этилмалтол 10%)', selected: false },
  { id: 1102, name: 'Flue Cured (Дымовых Обработанная)', selected: false },
  { id: 1103, name: 'French Vanilla (Французская Ваниль)', selected: false },
  { id: 1104, name: 'French Vanilla Creme (Французский Ванильный Крем)', selected: false },
  { id: 1105, name: 'French Vanilla Deluxe (Французская Ваниль Делюкс)', selected: false },
  { id: 1106, name: 'Fruit Circles (Фруктовые колечки)', selected: false },
  { id: 1107, name: 'Fruit Circles With Milk (Фруктовые колечки с молоком)', selected: false },
  { id: 1108, name: 'Fudge Brownie (Шоколадный кекс)', selected: false },
  { id: 1109, name: 'Gengerbread Cookie (Имбирный пряник)', selected: false },
  { id: 1110, name: 'Gin (Джин)', selected: false },
  { id: 1111, name: 'Ginger Ale (Имбирный Эль)', selected: false },
  { id: 1112, name: 'Graham Cracker (Грэхам Крекер)', selected: false },
  { id: 1113, name: 'Graham Cracker Clear (Чистый Грэхам Крекер)', selected: false },
  { id: 1114, name: 'Grape Juice (Виноградный Сок)', selected: false },
  { id: 1115, name: 'Greek Yogurt (Греческий Йогурт)', selected: false },
  { id: 1116, name: 'Green Apple (Зеленое Яблоко)', selected: false },
  { id: 1117, name: 'Green Tea (Зеленый Чай)', selected: false },
  { id: 1118, name: 'Guava (Гуава)', selected: false },
  { id: 1119, name: 'Gummy Candy (Конфета Мишки Гамми)', selected: false },
  { id: 1120, name: 'Hawaiian Drink (Гавайский Напиток)', selected: false },
  { id: 1121, name: 'Hazelnut (Лесной Орех)', selected: false },
  { id: 1122, name: 'Hazelnut Praline (Пралине Лесной Орех)', selected: false },
  { id: 1123, name: 'Hibiscus (Гибискус)', selected: false },
  { id: 1124, name: 'Hickory Smoke (Дымный Гикори)', selected: false },
  { id: 1125, name: 'Holiday Spice (Праздничные Специи)', selected: false },
  { id: 1126, name: 'Honey (Мед)', selected: false },
  { id: 1127, name: 'Honeydew (Нектар)', selected: false },
  { id: 1128, name: 'Honeysuckle (Жимолость)', selected: false },
  { id: 1129, name: 'Horchata (Орчата)', selected: false },
  { id: 1130, name: 'Horchata Smooth (Сглаженная Орчата)', selected: false },
  { id: 1131, name: 'Horehound (Хорхаунд)', selected: false },
  { id: 1132, name: 'Hpno Type (Гипнотический)', selected: false },
  { id: 1133, name: 'Huckleberry (Черника)', selected: false },
  { id: 1134, name: 'Irish Cream (Ирландский Крем (Айриш-крим))', selected: false },
  { id: 1135, name: 'Jackfruit (Джекфрут)', selected: false },
  { id: 1136, name: 'Jalapeno (Халапеньо)', selected: false },
  { id: 1137, name: 'Jamaican Rum (Ямайский Ром)', selected: false },
  { id: 1138, name: 'Kahlua & Cream (Крем и Калуа)', selected: false },
  { id: 1139, name: 'Kentucky Bourbon (Кентукийский Бурбон)', selected: false },
  { id: 1140, name: 'Kettle Corn (Вареная Кукуруза)', selected: false },
  { id: 1141, name: 'Key Lime (Лайм)', selected: false },
  { id: 1142, name: 'Kiwi (Double) (Двойной Киви)', selected: false },
  { id: 1143, name: 'Koolada 10% (Охлаждающая присадка)', selected: false },
  { id: 1144, name: 'Lemon (Water Soluble) (Лимон для разведения в воде)', selected: false },
  { id: 1145, name: 'Lemon Lime (Лимонад)', selected: false },
  { id: 1146, name: 'Lime (Лайм)', selected: false },
  { id: 1147, name: 'Lucky Leprechaun Cereal (Счастливый Лепрекон)', selected: false },
  { id: 1148, name: 'Lychee (Личи )', selected: false },
  { id: 1149, name: 'Malted Milk (Conc) (Солодовое Молоко (Концентрат))', selected: false },
  { id: 1150, name: 'Mango (Манго)', selected: false },
  { id: 1151, name: 'Maple (Клен)', selected: false },
  { id: 1152, name: 'Maple Syrup (Кленовый Сироп)', selected: false },
  { id: 1153, name: 'Maraschino Cherry (Мараскиновая вишня (черешня))', selected: false },
  { id: 1154, name: 'Marshmallow (Зефир)', selected: false },
  { id: 1155, name: 'Mary Jane (Мэри Джейн)', selected: false },
  { id: 1156, name: 'Menthol (Ментол)', selected: false },
  { id: 1157, name: 'Meringue (Безе)', selected: false },
  { id: 1158, name: 'Mexican Coffee (Мексиканский Кофе)', selected: false },
  { id: 1159, name: 'Mexican Liqueur (Мексиканский Ликер)', selected: false },
  { id: 1160, name: 'Mild Black (Темный Мягкий)', selected: false },
  { id: 1161, name: 'Milk Chocolate (Молочный Шоколад)', selected: false },
  { id: 1162, name: 'Mint Candy (Мятная Конфета)', selected: false },
  { id: 1163, name: 'Mocha (Мокка)', selected: false },
  { id: 1164, name: 'Mojito (Мохито)', selected: false },
  { id: 1165, name: 'Mojito Havana (Гаванский Мохито)', selected: false },
  { id: 1166, name: 'Molasses (Патока)', selected: false },
  { id: 1167, name: 'Musk Candy (Мускусная Конфета)', selected: false },
  { id: 1168, name: 'Nectarine (Нектарин)', selected: false },
  { id: 1169, name: 'Oatmeal Cookie (Овсяное Печенье)', selected: false },
  { id: 1170, name: 'Orange Cream (Апельсиновый Крем)', selected: false },
  { id: 1171, name: 'Orange Mandarin (Мандарин)', selected: false },
  { id: 1172, name: 'Papaya (Папайя)', selected: false },
  { id: 1173, name: 'Passion Fruit (Маракуйя)', selected: false },
  { id: 1174, name: 'Peach (Персик)', selected: false },
  { id: 1175, name: 'Peach (Juicy) (Сочный Персик)', selected: false },
  { id: 1176, name: 'Peanut Butter (Арахисовое Масло)', selected: false },
  { id: 1177, name: 'Pear (Груша)', selected: false },
  { id: 1178, name: 'Pear Candy (Грушевая Конфета)', selected: false },
  { id: 1179, name: 'Pecan (Орех-Пекан)', selected: false },
  { id: 1180, name: 'Peppermint (Перечная Мята)', selected: false },
  { id: 1181, name: 'Philippine Mango (Филиппинское Манго)', selected: false },
  { id: 1182, name: 'Pie Crust (Хрустящий Пирог)', selected: false },
  { id: 1183, name: 'Pina Colada (Пина Колада)', selected: false },
  { id: 1184, name: 'Pineapple (Ананас)', selected: false },
  { id: 1185, name: 'Pizza (Пицца)', selected: false },
  { id: 1186, name: 'Plum (Слива)', selected: false },
  { id: 1187, name: 'Pomegranate (Гранат )', selected: false },
  { id: 1188, name: 'Pomegranate Deluxe (Гранат Делюкс)', selected: false },
  { id: 1189, name: 'Popcorn (Попкорн)', selected: false },
  { id: 1190, name: 'Pralines & Cream (Пралине и Сливки)', selected: false },
  { id: 1191, name: 'Pumpkin (Тыква)', selected: false },
  { id: 1192, name: 'Pumpkin Spice (Тыква с Перцем)', selected: false },
  { id: 1193, name: 'Quince (Айва)', selected: false },
  { id: 1194, name: 'Rainbow Drops (Капли Радуги)', selected: false },
  { id: 1195, name: 'Raisin (Изюм)', selected: false },
  { id: 1196, name: 'Raspberry (Малина)', selected: false },
  { id: 1197, name: 'Raspberry (Sweet) (Сладкая Малина)', selected: false },
  { id: 1198, name: 'Red Licorice (Красная Солодка)', selected: false },
  { id: 1199, name: 'Red Oak (Красный Дуб)', selected: false },
  { id: 1200, name: 'Red Type (Красный Тип)', selected: false },
  { id: 1201, name: 'Red Type 2 (Красный Тип 2)', selected: false },
  { id: 1202, name: 'Red Velvet Cake (Пирог Красный Бархат)', selected: false },
  { id: 1203, name: 'Rice Crunchies (Рисовые хрустики)', selected: false },
  { id: 1204, name: 'Ripe Banana (Спелый Банан)', selected: false },
  { id: 1205, name: 'Root Beer (Рутовое Пиво)', selected: false },
  { id: 1206, name: 'Rose Candy (Конфета с Розой)', selected: false },
  { id: 1207, name: 'RY4 (Руян)', selected: false },
  { id: 1208, name: 'RY4 Asian (Азиатский Руян)', selected: false },
  { id: 1209, name: 'RY4 Double (Двойной Руян)', selected: false },
  { id: 1210, name: 'Sea Buckthorn (Облепиха)', selected: false },
  { id: 1211, name: 'Silly Rabbit Cereal (Хлопья Глупенький Кролик)', selected: false },
  { id: 1212, name: 'Smooth (Смягчитель)', selected: false },
  { id: 1213, name: 'Sour (Кислота)', selected: false },
  { id: 1214, name: 'Spearmint (Мята Садовая)', selected: false },
  { id: 1215, name: 'Strawberry (Клубника)', selected: false },
  { id: 1216, name: 'Strawberry (Ripe) (Спелая Клубника)', selected: false },
  { id: 1217, name: 'Swedish Gummy (Шведская Мармеладка)', selected: false },
  { id: 1218, name: 'Sweet Cream (Сладкий Крем)', selected: false },
  { id: 1219, name: 'Sweet Tea (Сладкий Чай)', selected: false },
  { id: 1220, name: 'Sweetener (Подсластитель)', selected: false },
  { id: 1221, name: 'Taro (Таро )', selected: false },
  { id: 1222, name: 'Tiramisu (Тирамису)', selected: false },
  { id: 1223, name: 'Toasted Almond (Поджаренный Миндаль)', selected: false },
  { id: 1224, name: 'Toasted Marshmallow (Поджареный Зефир)', selected: false },
  { id: 1225, name: 'Tobacco (Табак)', selected: false },
  { id: 1226, name: 'Tobacco Base (Табачная База)', selected: false },
  { id: 1227, name: 'Turkish (Турецкий)', selected: false },
  { id: 1228, name: 'Tutti-Frutti (Тутти-Фрутти)', selected: false },
  { id: 1229, name: 'Vanilla (Bourbon) (Ваниль с бурбоном)', selected: false },
  { id: 1230, name: 'Vanilla Bean Gelato (Мороженое с ванильным стручком)', selected: false },
  { id: 1231, name: 'Vanilla Bean Ice Cream (Мороженное с ванильным стручком)', selected: false },
  { id: 1232, name: 'Vanilla Cupcake (Ванильный кекс)', selected: false },
  { id: 1233, name: 'Vanilla Custard (Ванильный заварной крем)', selected: false },
  { id: 1234, name: 'Vanilla Swirl (Ванильное Мороженое Рожок)', selected: false },
  { id: 1235, name: 'Vanillin 10% (Ванилин)', selected: false },
  { id: 1236, name: 'Violet Candy (Фиолетовая Пастилка )', selected: false },
  { id: 1237, name: 'Waffle (Вафля)', selected: false },
  { id: 1238, name: 'Waffle (Belgian) (Бельгийская вафля)', selected: false },
  { id: 1239, name: 'Watermelon (Арбуз)', selected: false },
  { id: 1240, name: 'Watermelon Candy (Арбузная Конфета)', selected: false },
  { id: 1241, name: 'Western (Западный)', selected: false },
  { id: 1242, name: 'Whipped Cream (Взбитый Крем)', selected: false },
  { id: 1243, name: 'White Chocolate (Белый шоколад)', selected: false },
  { id: 1244, name: 'Wintergreen (Винтергрен)', selected: false },
  { id: 1245, name: 'Yam (Батат)', selected: false },
]

export const aromsListCapella = [
  { id: 2001, name: 'Amaretto (Амаретто)', selected: false },
  { id: 2002, name: 'Anise (Анис)', selected: false },
  { id: 2003, name: 'Apple Pie (Яблочный Пирог)', selected: false },
  { id: 2004, name: 'Apple Pie v2 (Яблочный пирог v2)', selected: false },
  { id: 2005, name: 'Apricot (Абрикос)', selected: false },
  { id: 2006, name: 'Bacon (Бекон)', selected: false },
  { id: 2007, name: 'Banana (Банан)', selected: false },
  { id: 2008, name: 'Banana Split (Банановый Сплит)', selected: false },
  { id: 2009, name: 'Bavarian Cream (Баварский Крем)', selected: false },
  { id: 2010, name: 'Blackberry (Ежевика)', selected: false },
  { id: 2011, name: 'Blue Raspberry Cotton Candy (Сахарная Вата из Голубой Малины)', selected: false },
  { id: 2012, name: 'Blueberry (Черника)', selected: false },
  { id: 2013, name: 'Blueberry Cinnamon Crumble (Чернично-Коричный Рассыпчатый Пирог)', selected: false },
  { id: 2014, name: 'Blueberry Jam (Черничный Джем)', selected: false },
  { id: 2015, name: 'Blueberry Pomegranate (Черника с Гранатом)', selected: false },
  { id: 2016, name: 'Blueberry Pomegranate with Stevia (Черника Гранат со стевией)', selected: false },
  { id: 2017, name: 'Bold Tobacco (Жирный Табак)', selected: false },
  { id: 2018, name: 'Boston Cream Pie (Бостонский Кремовый Пирог)', selected: false },
  { id: 2019, name: 'Boston Cream Pie v2 (Бостон Cream Pie v2)', selected: false },
  { id: 2020, name: 'Bubble Gum (Жвачка)', selected: false },
  { id: 2021, name: 'Butter (Масло)', selected: false },
  { id: 2022, name: 'Butter Cream (Масляный Крем)', selected: false },
  { id: 2023, name: 'Cake Batter (Тесто для Пирога)', selected: false },
  { id: 2024, name: 'Cantaloupe (Дыня)', selected: false },
  { id: 2025, name: 'Cappuccino (Капучино)', selected: false },
  { id: 2026, name: 'Cappuccino v2 (Капучино Версия 2)', selected: false },
  { id: 2027, name: 'Caramel (Карамель)', selected: false },
  { id: 2028, name: 'Caramel v2 (Карамель Версия 2)', selected: false },
  { id: 2029, name: 'Cereal 27 (Хлопья)', selected: false },
  { id: 2030, name: 'Chai Tea (Чай Масала)', selected: false },
  { id: 2031, name: 'Cherry Cola (Черри Кола)', selected: false },
  { id: 2032, name: 'Chocolate Caramel Nut (Шоколад Карамель орех)', selected: false },
  { id: 2033, name: 'Chocolate Coconut Almond (Шоколад с Кокосом и Миндалем)', selected: false },
  { id: 2034, name: 'Chocolate Fudge Brownie (Шоколадный Кекс)', selected: false },
  { id: 2035, name: 'Chocolate Fudge Brownie v2 (Fudge шоколада Домовой v2)', selected: false },
  { id: 2036, name: 'Chocolate Glazed Doughnut (Пончик с Шоколадной Глазурью)', selected: false },
  { id: 2037, name: 'Chocolate Raspberry (Шоколадная Малина)', selected: false },
  { id: 2038, name: 'Cinnamon Coffee Cake (Кофейный Пирог с Корицей)', selected: false },
  { id: 2039, name: 'Cinnamon Danish (Датская корица)', selected: false },
  { id: 2040, name: 'Cinnamon Danish Swirl (Датский Коричный Рогалик)', selected: false },
  { id: 2041, name: 'Cinnamon Danish Swirl v2 (Корица датский Вихревой v2)', selected: false },
  { id: 2042, name: 'Coconut (Кокос)', selected: false },
  { id: 2043, name: 'Cola (Кола)', selected: false },
  { id: 2044, name: 'Cola Flavor (Вкусом колы)', selected: false },
  { id: 2045, name: 'Cola Flavor Concentrate (Кола Вкус концентрат)', selected: false },
  { id: 2046, name: 'Concord Grape (Виноград сорт Конкорд)', selected: false },
  { id: 2047, name: 'Concord Grape with Stevia (Конкорд винограда со стевией)', selected: false },
  { id: 2048, name: 'Cool Mint (Охлаждающая Мята)', selected: false },
  { id: 2049, name: 'Cool Mint Natural (Охлаждающая Мята (Натуральная))', selected: false },
  { id: 2050, name: 'Cranberry (Клюква)', selected: false },
  { id: 2051, name: 'Creamy Yogurt (Кремовый Йогурт)', selected: false },
  { id: 2052, name: 'Crispy Bacon (Хрустящим беконом)', selected: false },
  { id: 2053, name: 'Cucumber (Огурец)', selected: false },
  { id: 2054, name: 'Cup a Joe (Чашечка Джо)', selected: false },
  { id: 2055, name: 'Double Apple (Двойное Яблоко)', selected: false },
  { id: 2056, name: 'Double Chocolate (Двойной Шоколад)', selected: false },
  { id: 2057, name: 'Double Chocolate v2 (Двойной Шоколад v2)', selected: false },
  { id: 2058, name: 'Double Watermelon (Двойной Арбуз)', selected: false },
  { id: 2059, name: 'Dragonfruit (Питайя)', selected: false },
  { id: 2060, name: 'Dutch Chocolate Mint (Датский Шоколад с Мятой)', selected: false },
  { id: 2061, name: 'Egg Nog (Эгг-ног)', selected: false },
  { id: 2062, name: 'Energy Drink (Энергетический Напиток)', selected: false },
  { id: 2063, name: 'Espresso (Эспрессо)', selected: false },
  { id: 2064, name: 'Fig (Инжир (Фига))', selected: false },
  { id: 2065, name: 'French Toast (Французский Тост)', selected: false },
  { id: 2066, name: 'French Vanilla (Французская Ваниль)', selected: false },
  { id: 2067, name: 'French Vanilla v2 (Французский ванильный v2)', selected: false },
  { id: 2068, name: 'GingerBread (Имбирный Пряник)', selected: false },
  { id: 2069, name: 'Glazed Doughnut (Пончик с Глазурью)', selected: false },
  { id: 2070, name: 'Golden Butter (Сливочное Масло)', selected: false },
  { id: 2071, name: 'Golden Pineapple (Золотой Ананас)', selected: false },
  { id: 2072, name: 'Graham Cracker (Крекер Грэма)', selected: false },
  { id: 2073, name: 'Graham Cracker v2 (Грэм крекер v2)', selected: false },
  { id: 2074, name: 'Grape (Виноград)', selected: false },
  { id: 2075, name: 'Grapefruit (Грейпфрут)', selected: false },
  { id: 2076, name: 'Greek Yogurt (Греческий Йогурт)', selected: false },
  { id: 2077, name: 'Green Apple (Зеленое Яблоко)', selected: false },
  { id: 2078, name: 'Grenadine (Гренадин)', selected: false },
  { id: 2079, name: 'Harvest Berry (Ягодный Урожай)', selected: false },
  { id: 2080, name: 'Hazelnut (Фундук)', selected: false },
  { id: 2081, name: 'Hazelnut v2 (Фундук v2)', selected: false },
  { id: 2082, name: 'Hibiscus (Гибискус)', selected: false },
  { id: 2083, name: 'Honeydew Melon (Зимняя Дыня)', selected: false },
  { id: 2084, name: 'Horchata (Орчата)', selected: false },
  { id: 2085, name: 'Hot Cinnamon Candy (Острая Коричная Конфета)', selected: false },
  { id: 2086, name: 'Hot Cocoa (Горячий Какао)', selected: false },
  { id: 2087, name: 'Irish Cream (Ирландский Крем)', selected: false },
  { id: 2088, name: 'Italian Lemon Sicily (Итальяно-Сицилийский Лимон)', selected: false },
  { id: 2089, name: 'Jelly Candy (Мармелад)', selected: false },
  { id: 2090, name: 'Juicy Lemon (Сочный Лимон)', selected: false },
  { id: 2091, name: 'Juicy Orange (Сочный Апельсин)', selected: false },
  { id: 2092, name: 'Juicy Peach (Сочный Персик)', selected: false },
  { id: 2093, name: 'Kiwi Strawberry (Киви с Клубникой)', selected: false },
  { id: 2094, name: 'Kiwi Strawberry with Stevia (Киви Клубника со стевией)', selected: false },
  { id: 2095, name: 'Lemon Lime (Лимон и Лайм)', selected: false },
  { id: 2096, name: 'Lemon Meringue Pie (Пирог с Лимонным Безе)', selected: false },
  { id: 2097, name: 'Lemon Meringue Pie v2 (Лимонный пирог безе v2)', selected: false },
  { id: 2098, name: 'Maple (Pancake) Syrup (Кленовый Сироп)', selected: false },
  { id: 2099, name: 'Maple Pancake Syrup (Клен Блин Сироп)', selected: false },
  { id: 2100, name: 'Maple Syrup (Кленовый Сироп)', selected: false },
  { id: 2101, name: 'Marshmallow (Зефир)', selected: false },
  { id: 2102, name: 'Medium Tobacco (Средний Табак)', selected: false },
  { id: 2103, name: 'Menthol (Ментол)', selected: false },
  { id: 2104, name: 'Milk Chocolate Toffee (Молочный шоколад Ириски)', selected: false },
  { id: 2105, name: 'New York Cheesecake (Чизкейк Нью-Йорк)', selected: false },
  { id: 2106, name: 'Orange Cream (Апельсиновый Крем)', selected: false },
  { id: 2107, name: 'Orange Creamsicle (Апельсиновый Фруктовый Лед)', selected: false },
  { id: 2108, name: 'Orange Mango (Апельсин и Манго)', selected: false },
  { id: 2109, name: 'Orange Mango with Stevia (Оранжевый Манго со стевией)', selected: false },
  { id: 2110, name: 'Passion Fruit (Маракуйя)', selected: false },
  { id: 2111, name: 'Peach (Персик)', selected: false },
  { id: 2112, name: 'Peach with Stevia (Персик со Стевией)', selected: false },
  { id: 2113, name: 'Peaches & Cream (Персики с Кремом)', selected: false },
  { id: 2114, name: 'Peaches & Cream v2 (Персики и крем v2)', selected: false },
  { id: 2115, name: 'Peanut Butter (Арахисовое Масло)', selected: false },
  { id: 2116, name: 'Pear (Груша)', selected: false },
  { id: 2117, name: 'Pear with Stevia (Груша со Стевией)', selected: false },
  { id: 2118, name: 'Peppermint (Перечная Мята)', selected: false },
  { id: 2119, name: 'Pina Colada (Пина Колада)', selected: false },
  { id: 2120, name: 'Pina Colada v2 (Пина Колада v2)', selected: false },
  { id: 2121, name: 'Pink Lemonade (Розовый Лимонад)', selected: false },
  { id: 2122, name: 'Pomegranate (Гранат)', selected: false },
  { id: 2123, name: 'Pomegranate v2 (Гранат v2)', selected: false },
  { id: 2124, name: 'Popcorn (Поп-корн)', selected: false },
  { id: 2125, name: 'Pralines & Cream (Пралине с Кремом)', selected: false },
  { id: 2126, name: 'Pumpkin Pie (Spice) (Тыквенный Пирог со Специями)', selected: false },
  { id: 2127, name: 'Pumpkin Pie Spice (Тыквенный пирог специй)', selected: false },
  { id: 2128, name: 'Raspberry (Малина)', selected: false },
  { id: 2129, name: 'Raspberry v2 (Малина v2)', selected: false },
  { id: 2130, name: 'Root Beer (Корневое Пиво)', selected: false },
  { id: 2131, name: 'Simply Vanilla (Просто Ваниль)', selected: false },
  { id: 2132, name: 'Spearmint (Мята)', selected: false },
  { id: 2133, name: 'Strawberries & Cream (Клубника со Сливками)', selected: false },
  { id: 2134, name: 'Strawberry Taffy (Клубничная Ириска)', selected: false },
  { id: 2135, name: 'Sugar Cookie (Сахарное печенье)', selected: false },
  { id: 2136, name: 'Sugar Cookie v2 (Сахарное печенье v2)', selected: false },
  { id: 2137, name: 'Sweet Cream (Сладкий Крем)', selected: false },
  { id: 2138, name: 'Sweet Guava (Сладкая Гуава)', selected: false },
  { id: 2139, name: 'Sweet Lychee (Сладкий Личи)', selected: false },
  { id: 2140, name: 'Sweet Mango (Сладкий Манго)', selected: false },
  { id: 2141, name: 'Sweet Strawberry (Сладкая Клубника)', selected: false },
  { id: 2142, name: 'Sweet Tangerine (Сладкий Мандарин)', selected: false },
  { id: 2143, name: 'Sweet Tea (Сладкий Чай)', selected: false },
  { id: 2144, name: 'Sweet Watermelon (Сладкий Арбуз)', selected: false },
  { id: 2145, name: 'Toasted Almond (Поджаренный Миндаль)', selected: false },
  { id: 2146, name: 'True Tobacco (Правда Табак)', selected: false },
  { id: 2147, name: 'Vanilla Bean Ice Cream (Мороженое с Ванильным Стручком)', selected: false },
  { id: 2148, name: 'Vanilla Cupcake (Ванильный Кекс)', selected: false },
  { id: 2149, name: 'Vanilla Cupcake v2 (Ванильный кекс v2)', selected: false },
  { id: 2150, name: 'Vanilla Custard (Ванильный Заварной Крем (Кастард))', selected: false },
  { id: 2151, name: 'Vanilla Custard v2 (Ванильный крем v2)', selected: false },
  { id: 2152, name: 'Vanilla Whipped Cream (Взбитый Ванильный Крем)', selected: false },
  { id: 2153, name: 'Waffle (Вафля)', selected: false },
  { id: 2154, name: 'Wild Cherry with Stevia (Вишня со Стевией)', selected: false },
  { id: 2155, name: 'Yellow Peach (Желтый Персик)', selected: false },
]

export const aromsListFlavourArt = [
  { id: 3001, name: 'Almond (Миндаль)', selected: false },
  { id: 3002, name: 'Apple Fuji (Сорт Яблок Фуджи)', selected: false },
  { id: 3003, name: 'Apple Pie (Яблочный Пирог (Шарлотка))', selected: false },
  { id: 3004, name: 'Apricot (Абрикос)', selected: false },
  { id: 3005, name: 'Bergamot (Бергамот)', selected: false },
  { id: 3006, name: 'Bilberry (Черника)', selected: false },
  { id: 3007, name: 'Black Cherry (Черная Вишня)', selected: false },
  { id: 3008, name: 'Black Tea (Черный Чай)', selected: false },
  { id: 3009, name: 'Burley (Берли)', selected: false },
  { id: 3010, name: 'Butterscotch (Ириска)', selected: false },
  { id: 3011, name: 'Cappuccino (Кофе Капучино)', selected: false },
  { id: 3012, name: 'Caramel (Карамель)', selected: false },
  { id: 3013, name: 'Catalan Cream (Каталонский Крем)', selected: false },
  { id: 3014, name: 'Chocolate (Шоколад)', selected: false },
  { id: 3015, name: 'Cinnamon Ceylon (Корица)', selected: false },
  { id: 3016, name: 'Coconut (Кокос)', selected: false },
  { id: 3017, name: 'Cola (Кола)', selected: false },
  { id: 3018, name: 'Cookie (Печенье)', selected: false },
  { id: 3019, name: 'Cream Custard (Заварной Крем)', selected: false },
  { id: 3020, name: 'Cream Fresh (Свежие Взбитые Сливки)', selected: false },
  { id: 3021, name: 'Cucumber (Огурец)', selected: false },
  { id: 3022, name: 'Forrest Mix (Лесные Ягоды)', selected: false },
  { id: 3023, name: 'Grapefruit (Грейпфрут)', selected: false },
  { id: 3024, name: 'Guava (Гуава)', selected: false },
  { id: 3025, name: 'Hazelnut (Фундук)', selected: false },
  { id: 3026, name: 'Honey (Мед)', selected: false },
  { id: 3027, name: 'JOY (Десертный Микс (Выпечка, Торт))', selected: false },
  { id: 3028, name: 'Kiwi (Киви)', selected: false },
  { id: 3029, name: 'Lemon Sicily (Сицилийский Лимон)', selected: false },
  { id: 3030, name: 'Lime Tahity Cold Pressed (Лайм Холодного Отжима)', selected: false },
  { id: 3031, name: 'Lime Tahity Distilled (Таитинский Лайм)', selected: false },
  { id: 3032, name: 'Lychee (Личи)', selected: false },
  { id: 3033, name: 'Mandarin (Мандарин)', selected: false },
  { id: 3034, name: 'Mango (Манго)', selected: false },
  { id: 3035, name: 'Maple Syrup (Кленовый Сироп)', selected: false },
  { id: 3036, name: 'Marshmallow (Зефир)', selected: false },
  { id: 3037, name: 'Maxx Blend (Макс Бленд)', selected: false },
  { id: 3038, name: 'Meringue (Безе)', selected: false },
  { id: 3039, name: 'Nut Mix (Ореховый Микс)', selected: false },
  { id: 3040, name: 'Oak Wood (Дубовая Древесина)', selected: false },
  { id: 3041, name: 'Orange (Апельсин)', selected: false },
  { id: 3042, name: 'Passionfruit (Маракуйя)', selected: false },
  { id: 3043, name: 'Peach (Персик)', selected: false },
  { id: 3044, name: 'Pear (Груша)', selected: false },
  { id: 3045, name: 'Pistacchio (Фисташки)', selected: false },
  { id: 3046, name: 'Raspberry (Малина)', selected: false },
  { id: 3047, name: 'Strawberry (Клубника)', selected: false },
  { id: 3048, name: 'Tea Green (Зеленый Чай)', selected: false },
  { id: 3049, name: 'Tiramisu (Тирамису)', selected: false },
  { id: 3050, name: 'Torrone (Десерт - Туррон)', selected: false },
  { id: 3051, name: 'Tutti Frutti (Тутти Фрутти (Жевательная Резинка Фруктовая))', selected: false },
  { id: 3052, name: 'Vanilla Bourbon (Ваниль Бурбон)', selected: false },
  { id: 3053, name: 'Vanilla Classic (Ванильный Классическая)', selected: false },
  { id: 3054, name: 'Vanilla Tahity (Ваниль Таитинская)', selected: false },
  { id: 3055, name: 'Vienna Cream (Венский Крем)', selected: false },
  { id: 3056, name: 'Watermelon (Арбуз)', selected: false },
  { id: 3057, name: 'Wayne Walker (Уэйн Уокер)', selected: false },
  { id: 3058, name: 'White Peach (Белый Персик)', selected: false },
]


