const aromsList = [
  {id: 'Absinthe (Абсент)', name: 'Absinthe (Абсент)' },
  {id: 'Acai (Ягода асаи)', name: 'Acai (Ягода асаи)' },
  {id: 'Acetyl Pyrazine (Ацетил пиразин)', name: 'Acetyl Pyrazine (Ацетил пиразин)' },
  {id: 'Almond (Миндаль)', name: 'Almond (Миндаль)' },
  {id: 'Apple (Яблоко)', name: 'Apple (Яблоко)' },
  {id: 'Apple (tart granny smith) (Яблоко (Гренни Смит))', name: 'Apple (tart granny smith) (Яблоко (Гренни Смит))' },
  {id: 'Apple Candy (Яблочный мармелад)', name: 'Apple Candy (Яблочный мармелад)' },
  {id: 'Apple Pie (Яблочный пирог)', name: 'Apple Pie (Яблочный пирог)' },
  {id: 'Apricot (Абрикос)', name: 'Apricot (Абрикос)' },
  {id: 'Banana (Банан)', name: 'Banana (Банан)' },
  {id: 'Banana Cream (Банановый крем)', name: 'Banana Cream (Банановый крем)' },
  {id: 'Banana Nut Bread (Банановый хлеб)', name: 'Banana Nut Bread (Банановый хлеб)' },
  {id: 'Bananas Foster (Банановый фостер)', name: 'Bananas Foster (Банановый фостер)' },
  {id: 'Bavarian Cream (Баварский крем)', name: 'Bavarian Cream (Баварский крем)' },
  {id: 'Berry Crunch (Ягодные хлопья)', name: 'Berry Crunch (Ягодные хлопья)' },
  {id: 'Bitter Nut Extra (Горький орех)', name: 'Bitter Nut Extra (Горький орех)' },
  {id: 'Bittersweet Chocolate (Биттерсвит шоколад)', name: 'Bittersweet Chocolate (Биттерсвит шоколад)' },
  {id: 'Black Cherry (Черешня)', name: 'Black Cherry (Черешня)' },
  {id: 'Black Currant (Черная смородина)', name: 'Black Currant (Черная смородина)' },
  {id: 'Black Honey (Черный мед и табак)', name: 'Black Honey (Черный мед и табак)' },
  {id: 'Black Tea (Черный чай)', name: 'Black Tea (Черный чай)' },
  {id: 'Blackberry (Ежевика)', name: 'Blackberry (Ежевика)' },
  {id: 'Blue Raspberry (Голубая малина)', name: 'Blue Raspberry (Голубая малина)' },
  {id: 'Blueberry (Extra) (Черника)', name: 'Blueberry (Extra) (Черника)' },
  {id: 'Blueberry Candy (Черничные леденцы)', name: 'Blueberry Candy (Черничные леденцы)' },
  {id: 'Blueberry Wild (Дикая черника)', name: 'Blueberry Wild (Дикая черника)' },
  {id: 'Boysenberry (Шелковица )', name: 'Boysenberry (Шелковица )' },
  {id: 'Brandy (Бренди)', name: 'Brandy (Бренди)' },
  {id: 'Brown Sugar (Коричневый сахар)', name: 'Brown Sugar (Коричневый сахар)' },
  {id: 'Bubblegum (Жвачка)', name: 'Bubblegum (Жвачка)' },
  {id: 'Bubblegum (Fruity) (Жвачка (Фруктовая))', name: 'Bubblegum (Fruity) (Жвачка (Фруктовая))' },
  {id: 'Butter (Масло)', name: 'Butter (Масло)' },
  {id: 'Butterscotch (Ирис)', name: 'Butterscotch (Ирис)' },
  {id: 'Cantaloupe (Канталупа)', name: 'Cantaloupe (Канталупа)' },
  {id: 'Cappucсino (Каппучино)', name: 'Cappucсino (Каппучино)' },
  {id: 'Caramel (Карамель)', name: 'Caramel (Карамель)' },
  {id: 'Caramel (Original) (Карамель (Оригинальная))', name: 'Caramel (Original) (Карамель (Оригинальная))' },
  {id: 'Caramel Candy (Карамельная конфета)', name: 'Caramel Candy (Карамельная конфета)' },
  {id: 'Caramel Cappuccino (Карамель-каппучино)', name: 'Caramel Cappuccino (Карамель-каппучино)' },
  {id: 'Chai Tea (Чай)', name: 'Chai Tea (Чай)' },
  {id: 'Champagne (Шампанское)', name: 'Champagne (Шампанское)' },
  {id: 'Cheesecake (Чизкейк)', name: 'Cheesecake (Чизкейк)' },
  {id: 'Cheesecake (Graham Crust) (Чизкейк (корочка))', name: 'Cheesecake (Graham Crust) (Чизкейк (корочка))' },
  {id: 'Cherry Blossom (Цветущая вишня)', name: 'Cherry Blossom (Цветущая вишня)' },
  {id: 'Cherry Extract (Экстракт вишни)', name: 'Cherry Extract (Экстракт вишни)' },
  {id: 'Chocolate (Шоколад)', name: 'Chocolate (Шоколад)' },
  {id: 'Cinnamon (Корица)', name: 'Cinnamon (Корица)' },
  {id: 'Cinnamon Danish (Корица датская)', name: 'Cinnamon Danish (Корица датская)' },
  {id: 'Cinnamon Red Hot (Корица)', name: 'Cinnamon Red Hot (Корица)' },
  {id: 'Cinnamon Spice (Острая корица)', name: 'Cinnamon Spice (Острая корица)' },
  {id: 'Cinnamon Sugar Cookie (Печенье с корицей)', name: 'Cinnamon Sugar Cookie (Печенье с корицей)' },
  {id: 'Citrus Punch (Цитрусовый пунш)', name: 'Citrus Punch (Цитрусовый пунш)' },
  {id: 'Clove (Гвоздика)', name: 'Clove (Гвоздика)' },
  {id: 'Cocoa Rounds (Шоколадные шарики)', name: 'Cocoa Rounds (Шоколадные шарики)' },
  {id: 'Coconut (Кокос)', name: 'Coconut (Кокос)' },
  {id: 'Coconut (Extra) (Кокос (Экстра))', name: 'Coconut (Extra) (Кокос (Экстра))' },
  {id: 'Coconut Candy (Кокосовые конфеты)', name: 'Coconut Candy (Кокосовые конфеты)' },
  {id: 'Coffee (Кофе)', name: 'Coffee (Кофе)' },
  {id: 'Cotton Candy (Сладкая вата)', name: 'Cotton Candy (Сладкая вата)' },
  {id: 'Cranberry (Клюква)', name: 'Cranberry (Клюква)' },
  {id: 'Cream Soda (Крем-сода)', name: 'Cream Soda (Крем-сода)' },
  {id: 'Creme de Menthe (Сладкий мятный ликер)', name: 'Creme de Menthe (Сладкий мятный ликер)' },
  {id: 'Cucumber (Огурец)', name: 'Cucumber (Огурец)' },
  {id: 'Dairy/Milk (Молоко)', name: 'Dairy/Milk (Молоко)' },
  {id: 'DK Tobacco Base (Табак)', name: 'DK Tobacco Base (Табак)' },
  {id: 'Double Chocolate (Clear) (Двойной шоколад)', name: 'Double Chocolate (Clear) (Двойной шоколад)' },
  {id: 'Double Chocolate (Dark) (Двойной шоколад (Темный))', name: 'Double Chocolate (Dark) (Двойной шоколад (Темный))' },
  {id: 'Dragonfruit (Драгонфрут (питайя))', name: 'Dragonfruit (Драгонфрут (питайя))' },
  {id: 'Dulce de Leche (Сгущенное молоко)', name: 'Dulce de Leche (Сгущенное молоко)' },
  {id: 'Earl Grey Tea (Эрл-грей)', name: 'Earl Grey Tea (Эрл-грей)' },
  {id: 'Elderberry (Бузина)', name: 'Elderberry (Бузина)' },
  {id: 'Energy Drink (Энергетический напиток)', name: 'Energy Drink (Энергетический напиток)' },
  {id: 'English Toffee (Тоффи)', name: 'English Toffee (Тоффи)' },
  {id: 'Espresso (Эспрессо)', name: 'Espresso (Эспрессо)' },
  {id: 'Ethyl Maltol (Этил мальтол)', name: 'Ethyl Maltol (Этил мальтол)' },
  {id: 'French Vanilla (Французкая ваниль)', name: 'French Vanilla (Французкая ваниль)' },
  {id: 'French Vanilla Deluxe (Французкая ваниль (Делюкс))', name: 'French Vanilla Deluxe (Французкая ваниль (Делюкс))' },
  {id: 'Frosted Donut (Пончик)', name: 'Frosted Donut (Пончик)' },
  {id: 'Fruit Circles (Фруктовые кольца)', name: 'Fruit Circles (Фруктовые кольца)' },
  {id: 'Fruit Circles With Milk (Фруктовые кольца с молоком)', name: 'Fruit Circles With Milk (Фруктовые кольца с молоком)' },
  {id: 'Fruity Stick Gum (Жвачка (Fruity Stick))', name: 'Fruity Stick Gum (Жвачка (Fruity Stick))' },
  {id: 'Fudge Brownie (Брауни)', name: 'Fudge Brownie (Брауни)' },
  {id: 'Ginger Ale (Имбирный Эль)', name: 'Ginger Ale (Имбирный Эль)' },
  {id: 'Gingerbread (Имбирный пряник)', name: 'Gingerbread (Имбирный пряник)' },
  {id: 'Graham Cracker (Грэхем крекер)', name: 'Graham Cracker (Грэхем крекер)' },
  {id: 'Graham Cracker Clear (Грэхем крекер)', name: 'Graham Cracker Clear (Грэхем крекер)' },
  {id: 'Grape Candy (Виноградные леденцы)', name: 'Grape Candy (Виноградные леденцы)' },
  {id: 'Grape Juice (Виноградный сок)', name: 'Grape Juice (Виноградный сок)' },
  {id: 'Greek Yogurt (Греческий йогурт)', name: 'Greek Yogurt (Греческий йогурт)' },
  {id: 'Green Apple (Зеленое яблоко)', name: 'Green Apple (Зеленое яблоко)' },
  {id: 'Green Tea (Зеленый чай)', name: 'Green Tea (Зеленый чай)' },
  {id: 'Guava (Гуайява)', name: 'Guava (Гуайява)' },
  {id: 'Gummy Candy (Тянучки)', name: 'Gummy Candy (Тянучки)' },
  {id: 'Hazelnut (Лесной орех)', name: 'Hazelnut (Лесной орех)' },
  {id: 'Hibiscus (Гибискус)', name: 'Hibiscus (Гибискус)' },
  {id: 'Honey (Мед)', name: 'Honey (Мед)' },
  {id: 'Honeydew (Медовая дыня)', name: 'Honeydew (Медовая дыня)' },
  {id: 'Honeydew II (Медовая дыня (версия 2))', name: 'Honeydew II (Медовая дыня (версия 2))' },
  {id: 'Honeysuckle (Жимолость)', name: 'Honeysuckle (Жимолость)' },
  {id: 'Horehound (Шандра)', name: 'Horehound (Шандра)' },
  {id: 'Huckleberry (Хаклберри)', name: 'Huckleberry (Хаклберри)' },
  {id: 'Irish Cream (Ирландские сливки)', name: 'Irish Cream (Ирландские сливки)' },
  {id: 'Jackfruit (Джекфрут)', name: 'Jackfruit (Джекфрут)' },
  {id: 'Jamaican Rum (Ямайский ром)', name: 'Jamaican Rum (Ямайский ром)' },
  {id: 'Kalua and Cream (Калуа и сливки)', name: 'Kalua and Cream (Калуа и сливки)' },
  {id: 'Kentucky Bourbon (Бурбон из Кентукки)', name: 'Kentucky Bourbon (Бурбон из Кентукки)' },
  {id: 'Key Lime (Лайм)', name: 'Key Lime (Лайм)' },
  {id: 'Kiwi (Киви)', name: 'Kiwi (Киви)' },
  {id: 'Kiwi (Double) (Киви (двойной))', name: 'Kiwi (Double) (Киви (двойной))' },
  {id: 'Koolada 10 PG (Кулада)', name: 'Koolada 10 PG (Кулада)' },
  {id: 'Lemon (water soluble) (Лимон)', name: 'Lemon (water soluble) (Лимон)' },
  {id: 'Lemon 2 (Лимон (Версия 2))', name: 'Lemon 2 (Лимон (Версия 2))' },
  {id: 'Lemon Lime (Лимон-лайм)', name: 'Lemon Lime (Лимон-лайм)' },
  {id: 'Lemon Lime 2 (Лимон лайм (версия 2))', name: 'Lemon Lime 2 (Лимон лайм (версия 2))' },
  {id: 'Lemonade Cookie (Лимонадное печенье)', name: 'Lemonade Cookie (Лимонадное печенье)' },
  {id: 'Lucky Leprechaun Cereal (Зефирные хлопья)', name: 'Lucky Leprechaun Cereal (Зефирные хлопья)' },
  {id: 'Lychee (Личи)', name: 'Lychee (Личи)' },
  {id: 'M Type Premium (Эм тайп премиум (табак))', name: 'M Type Premium (Эм тайп премиум (табак))' },
  {id: 'Malted milk (Сухое молоко)', name: 'Malted milk (Сухое молоко)' },
  {id: 'Mango (Манго)', name: 'Mango (Манго)' },
  {id: 'Maple Extract (Кленовый экстракт)', name: 'Maple Extract (Кленовый экстракт)' },
  {id: 'Maple Syrup (Кленовый сироп)', name: 'Maple Syrup (Кленовый сироп)' },
  {id: 'Marshmallow (Маршмеллоу)', name: 'Marshmallow (Маршмеллоу)' },
  {id: 'Mary Jane (Мери Джейн)', name: 'Mary Jane (Мери Джейн)' },
  {id: 'Menthol liquid (Ментол)', name: 'Menthol liquid (Ментол)' },
  {id: 'Meringue (Безе)', name: 'Meringue (Безе)' },
  {id: 'Milk Chocolate (Молочный шоколад)', name: 'Milk Chocolate (Молочный шоколад)' },
  {id: 'Mojito Havana (Мохито)', name: 'Mojito Havana (Мохито)' },
  {id: 'Molasses (Меласса)', name: 'Molasses (Меласса)' },
  {id: 'Musk Candy (Конфеты Musk Lifesaver)', name: 'Musk Candy (Конфеты Musk Lifesaver)' },
  {id: 'Nectarine (Нектарин)', name: 'Nectarine (Нектарин)' },
  {id: 'Oatmeal Cookie (Овсянное печенье)', name: 'Oatmeal Cookie (Овсянное печенье)' },
  {id: 'Orange Cream (Апельсиновый крем)', name: 'Orange Cream (Апельсиновый крем)' },
  {id: 'Orange Mandarin (Мандарин)', name: 'Orange Mandarin (Мандарин)' },
  {id: 'Pancake (Панкейк)', name: 'Pancake (Панкейк)' },
  {id: 'Papaya (Папайя)', name: 'Papaya (Папайя)' },
  {id: 'Passion Fruit (Маракуйя)', name: 'Passion Fruit (Маракуйя)' },
  {id: 'Peach (Персик)', name: 'Peach (Персик)' },
  {id: 'Peach (Juicy) (Сок персика)', name: 'Peach (Juicy) (Сок персика)' },
  {id: 'Peanut Butter (Арахисовое масло)', name: 'Peanut Butter (Арахисовое масло)' },
  {id: 'Pear (Груша)', name: 'Pear (Груша)' },
  {id: 'Pear Candy (Грушевые конфеты)', name: 'Pear Candy (Грушевые конфеты)' },
  {id: 'Pecan (Орех Пекан)', name: 'Pecan (Орех Пекан)' },
  {id: 'Peppermint (Перечная мята)', name: 'Peppermint (Перечная мята)' },
  {id: 'Pie Crust (Корочка пирога)', name: 'Pie Crust (Корочка пирога)' },
  {id: 'Pina Colada (Пина Колада)', name: 'Pina Colada (Пина Колада)' },
  {id: 'Pineapple (Ананас)', name: 'Pineapple (Ананас)' },
  {id: 'Pistachio (Фисташки)', name: 'Pistachio (Фисташки)' },
  {id: 'Plum (Слива)', name: 'Plum (Слива)' },
  {id: 'Pomegranate (Гранат)', name: 'Pomegranate (Гранат)' },
  {id: 'Pomegranate Deluxe (Гранат (делюкс))', name: 'Pomegranate Deluxe (Гранат (делюкс))' },
  {id: 'Popcorn (Попкорн)', name: 'Popcorn (Попкорн)' },
  {id: 'Quince (Айва)', name: 'Quince (Айва)' },
  {id: 'Rainbow Drops (Скиттлс)', name: 'Rainbow Drops (Скиттлс)' },
  {id: 'Raisin (Изюм)', name: 'Raisin (Изюм)' },
  {id: 'Raspberry (Малина)', name: 'Raspberry (Малина)' },
  {id: 'Raspberry (Sweet) (Сладкая малина)', name: 'Raspberry (Sweet) (Сладкая малина)' },
  {id: 'Red Licorice (Красная лакрица)', name: 'Red Licorice (Красная лакрица)' },
  {id: 'Red Type II Blend (Ред тайп (табак))', name: 'Red Type II Blend (Ред тайп (табак))' },
  {id: 'Rice Crunchies (Рисовые хлопья)', name: 'Rice Crunchies (Рисовые хлопья)' },
  {id: 'Ripe Banana (Спелый банан)', name: 'Ripe Banana (Спелый банан)' },
  {id: 'Root beer flavor (pg) (Рутбир)', name: 'Root beer flavor (pg) (Рутбир)' },
  {id: 'Root Beer Float (Рутбир Float)', name: 'Root Beer Float (Рутбир Float)' },
  {id: 'RY4 Double (RY4 (Табак (двойной)))', name: 'RY4 Double (RY4 (Табак (двойной)))' },
  {id: 'RY4 Type (RY4 (Табак))', name: 'RY4 Type (RY4 (Табак))' },
  {id: 'Slim Mint Cookie (Мятное печенье)', name: 'Slim Mint Cookie (Мятное печенье)' },
  {id: 'Smooth (Smooth)', name: 'Smooth (Smooth)' },
  {id: 'Sour (Кислый)', name: 'Sour (Кислый)' },
  {id: 'Spearmint (Мята колосистая)', name: 'Spearmint (Мята колосистая)' },
  {id: 'Strawberries and Cream (Клубника со сливками)', name: 'Strawberries and Cream (Клубника со сливками)' },
  {id: 'Strawberry (Клубника)', name: 'Strawberry (Клубника)' },
  {id: 'Strawberry (Ripe) (Спелая клубника)', name: 'Strawberry (Ripe) (Спелая клубника)' },
  {id: 'Swedish Gummy (Шведский гамми)', name: 'Swedish Gummy (Шведский гамми)' },
  {id: 'Sweet and Tart (Кофеты Sweet Tart (Холодок))', name: 'Sweet and Tart (Кофеты Sweet Tart (Холодок))' },
  {id: 'Sweet Cream (Сладкий крем)', name: 'Sweet Cream (Сладкий крем)' },
  {id: 'Sweet Tea (Сладкий чай)', name: 'Sweet Tea (Сладкий чай)' },
  {id: 'Sweetener (Подсластитель)', name: 'Sweetener (Подсластитель)' },
  {id: 'Tiramisu (Тирамису)', name: 'Tiramisu (Тирамису)' },
  {id: 'Toasted Almond (Жаренный миндаль)', name: 'Toasted Almond (Жаренный миндаль)' },
  {id: 'Toasted Marshmallow (Поджареный зефир)', name: 'Toasted Marshmallow (Поджареный зефир)' },
  {id: 'Tutti-Frutti (Тутти-фрутти)', name: 'Tutti-Frutti (Тутти-фрутти)' },
  {id: 'Vanilla (Bourbon) (Ваниль бурбон)', name: 'Vanilla (Bourbon) (Ваниль бурбон)' },
  {id: 'Vanilla Bean Gelato (Ванильный заварной крем)', name: 'Vanilla Bean Gelato (Ванильный заварной крем)' },
  {id: 'Vanilla Bean Ice Cream (Ванильное мороженное)', name: 'Vanilla Bean Ice Cream (Ванильное мороженное)' },
  {id: 'Vanilla Cupcake (Ванильный пирог)', name: 'Vanilla Cupcake (Ванильный пирог)' },
  {id: 'Vanilla Custard (Ванильный кастард)', name: 'Vanilla Custard (Ванильный кастард)' },
  {id: 'Vanilla Swirl (Ванильный рожок)', name: 'Vanilla Swirl (Ванильный рожок)' },
  {id: 'Vanillin 10 (PG) (Ванилин)', name: 'Vanillin 10 (PG) (Ванилин)' },
  {id: 'Waffle (Вафли)', name: 'Waffle (Вафли)' },
  {id: 'Waffle (Belgian) (Бельгийские вафли)', name: 'Waffle (Belgian) (Бельгийские вафли)' },
  {id: 'Watermelon (Арбуз)', name: 'Watermelon (Арбуз)' },
  {id: 'Watermelon Candy (Арбузные леденцы)', name: 'Watermelon Candy (Арбузные леденцы)' },
  {id: 'Western (Вестерн)', name: 'Western (Вестерн)' },
  {id: 'Whipped Cream (Взбитые сливки)', name: 'Whipped Cream (Взбитые сливки)' },
  {id: 'White Chocolate (Белый шоколад)', name: 'White Chocolate (Белый шоколад)' },
  {id: 'Wintergreen (Мятные кофеты)', name: 'Wintergreen (Мятные кофеты)' },
  {id: 'Yam (Ямс)', name: 'Yam (Ямс)' },  
]

export default aromsList;
